name: Detect new votes
on:
  push:
    branches:
      - shrey/cron-deploy
#   schedule:
#     - cron: "0-59/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install requirements
        run: |
          npm install dotenv node-fetch typescript
      - name: List files
        run: |
          ls scripts
      - name: Compile Typescript
        run: |
          tsc scripts/script.ts
      - name: List files
        run: |
          ls scripts
      - name: Run script
        run: |
          node scripts/script.js
        env:
          COMMUNITY_TOKEN: ${{ secrets.COMMUNITY_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
