name: Create Release PR
on:
  push:
    branches:
      - main
jobs:
  auto-pull-request:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "main"
          PULL_REQUEST_BRANCH: "release"
